### ISSUE TITLE
你们的dawn，什么时候可以自动加载最新改动的代码？

### ISSUE THREAD

**Issue by martinwithyou** [alibaba/dawn#130]
### 1. Information

OS & version | Node version | Dawn version
------------ | -------------| ---------------
your-version | your-version | your-version 

### 2. Problem

Describe your problems in as much detail as possible

### 3. Recurrence

The steps of problem recurrence

**Comment by Houfeng** [comment]
查看pipe.yml，可以这样写，

```yaml
name: server
port: 8080
autoOpen: false
name: browser-sync
```

浏览器的自动刷新是由中间件提供的能力，不是 dawn 本身的能力。
