### ISSUE TITLE
copy中间件的问题

### ISSUE THREAD

**Issue by meiwhu** [alibaba/dawn#82]
使用copy中间件：

``` yml
- name: copy
  files:
    ./build/lib/(0).js: ./lib/*.js
```

结果如下：
> copy: D:\tests\three\lib\three.min.js -> D:\tests\three\build\lib\three.js

其中min不见了？
